name: auto-checkin

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm install

      - run: node checkin.js
        env:
          COOKIE: ${{ secrets.COOKIE }}
